'use strict';

import path from 'path';
import browserSyncInstance from 'browser-sync';

// Init BrowserSync
const browserSync = browserSyncInstance.create();

// Paths Object
const paths = {
	imgs: {
		src: '_src/img/**/*.{png,jpg}',
		template: '_src/img/optimize/template-img/**/*.{png,jpg}',
		media: '_src/img/optimize/media-img/**/*.{png,jpg}',
		media_dest: '_src/img/optimize/media-img/',
		proc_dest: '_src/img/optimize/processed/',
		dest: 'images'
	},
	svgs: {
		src: '_src/img/svg/**/*.svg',
		dest: '_src/scss/general'
	},
	sprite: {
		src: '_src/img/sprite/**/*.{png,jpg}',
		dest: '_src/scss/general'
	},
	styles: {
		src: '_src/scss/**/*.{sass,scss}',
		dest: 'css'
	},
	scripts: {
		src: '_src/js/*.js',
		dest: 'js'
	},
	html: {
		src: ['**/*.{php,inc}', '!*safe_save*'] // files with safe_save are generated by some editors when saving the file
	},
	phpconfig: 'inc/gulp-config.inc'
};

// User Path
const userPath = path.resolve().split(path.sep);

// Generates Port Number When First Run ( Numbers 3000 through 4000 In Increments Of 10)
const browserSyncPort = Math.round((Math.random() * 1000 + 3000) / 10) * 10;



export {
	paths,
	userPath,
	browserSync,
	browserSyncPort
}