name: Deploy to Development Server

on:
  push:
    branches:
      - main # or your default branch name

jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Deploy to server
        env:
          SSH_DEV_PASSWORD: ${{ secrets.SSH_DEV_PASSWORD }}
          SSH_DEV_USERNAME: ${{ secrets.SSH_DEV_USERNAME }}
          SSH_DEV_HOST: ${{ secrets.SSH_DEV_HOST }}
          SERVER_WP_PATH: ${{ secrets.SERVER_WP_PATH }} # /var/www/html/wordpress
          SSH_DEV_PORT: ${{ secrets.SSH_DEV_PORT }}
        run: |
          sshpass -p "$SSH_DEV_PASSWORD" ssh -p $SSH_DEV_PORT -o StrictHostKeyChecking=no "$SSH_DEV_USERNAME"@"$SSH_DEV_HOST" << EOF
          cd "$SERVER_WP_PATH"
          git pull origin main          
          EOF

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: master

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
