name: Deploy to WordPress Server

on:
  push:
    branches:
      - main # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Install SSH key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.WATER_CALCULATOR_SSH_KEY }}
      #     known_hosts: ${{ secrets.SSH_HOST }}

      - name: Deploy to server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -p 14644 -o StrictHostKeyChecking=no ${{secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
          cd ${{ secrets.SERVER_WP_PATH }}
          whoami
          git clone https://github.com/GenThrive/WFC.git .
          EOF
