name: Deploy to WordPress Server

on:
  push:
    branches:
      - main # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.WATER_CALCULATOR_SSH_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=accept-new ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
            cd ${{ secrets.SERVER_WP_PATH }}
            git clone git@github.com:GenThrive/WFC.git .
          EOF
