name: CRON Job for Maintenance WordPress Server

on:
  #Run every night at 10:00 PM
  schedule:
    - cron: "0 22 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -p 14644 -o StrictHostKeyChecking=no ${{secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
          cd ${{ secrets.SERVER_WP_PATH }}
          git add .
          git commit -m "Automated deployment" 
          git push origin main
          EOF
